name: file_manger_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  #state management
  provider: ^6.1.1
  #injection
  get_it: ^7.6.4
  #internal storage
  get_storage: ^2.1.1
  permission_handler: ^11.3.1
  open_file: ^3.5.6
  #responsive
  flutter_screenutil: ^5.9.0
  #ui
  shimmer: ^3.0.0
  cherry_toast: ^1.10.0
  flutter_spinkit: ^5.2.0
  #helper
  intl: ^0.19.0
  file_picker: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
